### ISSUE TITLE
Marketplace future exceptions

### ISSUE THREAD

**Issue by KenwoodFox** [stephanlensky/hyacinth#58] opened 2023-12-05 18:57 UTC
Opening this issue to track marketplace future exception error.

Heres the output of running the new `get-marketplace-page-sample` test!

```
$ just get-marketplace-page-sample
/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/pyppeteer/us_keyboard_layout.py:73: SyntaxWarning: invalid escape sequence '\('
  'Digit9': {'keyCode': 57, 'code': 'Digit9', 'shiftKey': '\(', 'key': '9'},
2023-12-05 18:45:30 [14] [DEBUG] plugins.marketplace.client Loading marketplace search results
2023-12-05 18:45:30 [14] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/boston/motorcycles/?sortBy=creation_time_descend&exact=false
2023-12-05 18:45:35 [14] [DEBUG] plugins.marketplace.client Waiting for marketplace search results to render
2023-12-05 18:45:35 [14] [DEBUG] plugins.marketplace.client Marketplace search results rendered
Wrote tests/resources/marketplace-search-results-sample.html successfully
2023-12-05 18:45:36 [14] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/item/268741632849388/
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Runtime.releaseObject): Cannot find context with specified id')>
pyppeteer.errors.NetworkError: Protocol error (Runtime.releaseObject): Cannot find context with specified id
Wrote tests/resources/marketplace-result-details-sample.html successfully
```

Certainly looks like something is not working properly :c

The marketplace setup is also slightly confusing, did it pick boston at random? I live in NH

**Comment by stephanlensky** [comment] 2023-12-05 19:09
Cool, yeah I should have time but I'll see - also doing advent of code, so it depends how long that takes me 😛

**Comment by stephanlensky** [comment] 2023-12-08 23:01
👋 Hi, took me a bit longer than expected to get back to this.

Looks like this may be related to https://github.com/pyppeteer/pyppeteer/issues/89 and https://github.com/puppeteer/puppeteer/issues/1325, where an error is thrown if you try to interact with a page while it is still in the process of navigating.

I am not sure exactly what is causing the navigation in your case, so I pushed two possible solutions to new branches to speed up the testing process.

The branches are `disable-js` and `wait-for-network-idle`. Would you mind trying the following steps for each branch?

1. Check out branch
2. Launch the developer container as before and run `just get-marketplace-page-sample`
3. If it succeeds, run `pytest tests/plugins/marketplace/test_client.py` to ensure that the downloaded pages parse correctly.

If both the `just` command and `pytest` commands succeed, the issue will likely be fixed when you run the bot normally as well.

**Comment by KenwoodFox** [comment] 2023-12-11 00:44
## On the `wait-for-network-idle` branch

```
(hyacinth-py3.12) joyvan@5802b043362b:/app$ just get-marketplace-page-sample
/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/pyppeteer/us_keyboard_layout.py:73: SyntaxWarning: invalid escape sequence '\('
  'Digit9': {'keyCode': 57, 'code': 'Digit9', 'shiftKey': '\(', 'key': '9'},
2023-12-11 00:28:13 [14] [DEBUG] plugins.marketplace.client Loading marketplace search results
2023-12-11 00:28:13 [14] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/boston/motorcycles/?sortBy=creation_time_descend&exact=false
2023-12-11 00:28:35 [14] [DEBUG] plugins.marketplace.client Waiting for marketplace search results to render
2023-12-11 00:28:35 [14] [DEBUG] plugins.marketplace.client Marketplace search results rendered
Wrote tests/resources/marketplace-search-results-sample.html successfully
2023-12-11 00:28:35 [14] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/item/732568108306281/
2023-12-11 00:28:51 [14] [DEBUG] plugins.marketplace.client Getting page content for https://www.facebook.com/marketplace/item/732568108306281/
Wrote tests/resources/marketplace-result-details-sample.html successfully
(hyacinth-py3.12) joyvan@5802b043362b:/app$ pytest tests/plugins/marketplace/test_client.py
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.12.0, pytest-7.4.3, pluggy-1.3.0
rootdir: /app
configfile: pyproject.toml
plugins: asyncio-0.21.1, anyio-4.1.0, cov-4.1.0, mock-3.12.0
asyncio: mode=Mode.AUTO
collected 2 items                                                                                                                                                                                                  

tests/plugins/marketplace/test_client.py ..                                                                                                                                                                  [100%]

================================================================================================= warnings summary =================================================================================================
../home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/dateutil/tz/tz.py:37
  /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/dateutil/tz/tz.py:37: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    EPOCH = datetime.datetime.utcfromtimestamp(0)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================================== 2 passed, 1 warning in 0.89s ===========================================================================================
(hyacinth-py3.12) joyvan@5802b043362b:/app$
```

## On the `disable-js` branch

```
(hyacinth-py3.12) joyvan@190355c32b06:/app$ just get-marketplace-page-sample
/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/pyppeteer/us_keyboard_layout.py:73: SyntaxWarning: invalid escape sequence '\('
  'Digit9': {'keyCode': 57, 'code': 'Digit9', 'shiftKey': '\(', 'key': '9'},
2023-12-11 00:43:10 [14] [DEBUG] plugins.marketplace.client Loading marketplace search results
2023-12-11 00:43:10 [14] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/boston/motorcycles/?sortBy=creation_time_descend&exact=false
2023-12-11 00:43:39 [14] [DEBUG] plugins.marketplace.client Waiting for marketplace search results to render
2023-12-11 00:43:39 [14] [DEBUG] plugins.marketplace.client Marketplace search results rendered
Wrote tests/resources/marketplace-search-results-sample.html successfully
2023-12-11 00:43:40 [14] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/item/732568108306281/
2023-12-11 00:43:46 [14] [DEBUG] plugins.marketplace.client Getting page content for https://www.facebook.com/marketplace/item/732568108306281/
Wrote tests/resources/marketplace-result-details-sample.html successfully
(hyacinth-py3.12) joyvan@190355c32b06:/app$ pytest tests/plugins/marketplace/test_client.py
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.12.0, pytest-7.4.3, pluggy-1.3.0
rootdir: /app
configfile: pyproject.toml
plugins: asyncio-0.21.1, anyio-4.1.0, cov-4.1.0, mock-3.12.0
asyncio: mode=Mode.AUTO
collected 2 items                                                                                                                                                                                                  

tests/plugins/marketplace/test_client.py ..                                                                                                                                                                  [100%]

================================================================================================= warnings summary =================================================================================================
../home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/dateutil/tz/tz.py:37
  /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/dateutil/tz/tz.py:37: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    EPOCH = datetime.datetime.utcfromtimestamp(0)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================================================================== 2 passed, 1 warning in 0.85s ===========================================================================================
(hyacinth-py3.12) joyvan@190355c32b06:/app$
```

For some reason when i ran it the first time it just hung for 40 minutes.. but.. i rebooted the whole machine and it only took about 4 minutes for each branch!

**Comment by KenwoodFox** [comment] 2023-12-11 03:44
Let me switch over to that and start using it for prod :3, I'll let you know if it starts working!

**Comment by KenwoodFox** [comment] 2023-12-11 04:27
Possibly anecdotal but.. even after reboots and everything, the bot hasn't posted anything in a while.. I checked the logs and i keep seeing this..

![image](https://github.com/stephanlensky/hyacinth/assets/31870999/17d2cc32-79d1-4c2a-9d61-711fad75a969)

Is it just perpetually skipping?

**Comment by stephanlensky** [comment] 2023-12-11 05:17
Looks like the Marketplace polling job is taking too long to run. This is likely related to the fact that fetching a single result above was taking 4 minutes - that's way too slow for this.

I'm guessing the issue is a resource constraint somewhere - either your network is slow or the hardware you're running this on isn't powerful enough.

**Comment by stephanlensky** [comment] 2023-12-11 05:18
Either that, or Facebook is rate limiting you. Either way, not sure there is much I can do to help.

**Comment by KenwoodFox** [comment] 2023-12-11 05:22
> Looks like the Marketplace polling job is taking too long to run. This is likely related to the fact that fetching a single result above was taking 4 minutes - that's way too slow for this.
> 
> I'm guessing the issue is a resource constraint somewhere - either your network is slow or the hardware you're running this on isn't powerful enough.

Well, i can start with this. Let me do some benchmarking, see what i can come up with. Slowness would throw things off between what i see and what you see on your end. Either way, will keep you posted thanks so much

**Comment by KenwoodFox** [comment] 2023-12-11 05:59
Yeah idk what changed, i thought it was maybe something in the git a few days ago but, now craigslist doesn't work, marketplace doesn't work, just says skipped. When it says max running instances, it means the `browserless/chrome` container right? Can I do anything to diagnose see what its up to? Maybe its just stuck or my image is out of date?

**Comment by KenwoodFox** [comment] 2023-12-11 06:09
Browserless was repeating this for a while,
```
2023-12-11T05:48:44.970Z browserless:server Health check stats: CPU 16%,16% MEM: 24%,24%
2023-12-11T05:48:44.970Z browserless:server Current period usage: {"date":1702273424980,"error":0,"rejected":0,"successful":0,"timedout":0,"totalTime":0,"maxTime":0,"minTime":0,"meanTime":0,"maxConcurrent":0,"units":0}
```

Went ahead and ran your test again, the `just get-marketplace-page-sample`. That seemed to kick it into gear, fetched it no problem, test took about 8 seconds to complete

Health check kicked up one tick
```
2023-12-11T06:07:19.616Z browserless:server Health check stats: CPU 17%, MEM: 25%,
2023-12-11T06:07:19.616Z browserless:server Current period usage: {"date":1702274539574,"error":0,"rejected":0,"successful":1,"timedout":0,"totalTime":13550,"maxTime":13550,"minTime":13550,"meanTime":13550,"maxConcurrent":1,"units":1}
```

Wonder why `hyacinth-service` is not triggering? Anything change recently? Im on `main` right now.

And no sweat if this is a lot of back and forth, please, no need to rush

**Comment by stephanlensky** [comment] 2023-12-23 23:57
Hey, sorry it took me a while to get back to this. I'm still not sure exactly what is going wrong, but maybe I can help clarify what the log messages mean:

When you create a new search, a background job is started in Hyacinth which tries to poll that search every X seconds. As you might guess, "polling the search" involves loading the page in Browserless, grabbing the content, and parsing it to get results.

The log message you are seeing:

```
maximum number of running instances
```

occurs when the next poll job (in Hyacinth, not Browserless) tries to start before the previous one finished. The most likely culprit for this is that loading the pages in Browserless is taking much longer than expected. I'm not exactly what would be causing this, but given the resource usage on the container looks good, I think it's most likely a network speed/rate limiting issue.

If you want, you can try increasing the poll interval by modifying settings.py [here](https://github.com/stephanlensky/hyacinth/blob/main/hyacinth/settings.py#L47-L48), but there is definitely something else going on if a single search is taking longer than the current setting of 10 minutes.

BTW, I also just fixed a critical issue with Marketplace searches which would cause messages like

```
/app/plugins/marketplace/client.py:46: RuntimeWarning: coroutine '_navigate_to_search_results' was never awaited
  _navigate_to_search_results(page, search_params.location, search_params.category)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

sorry this one slipped by me, stupid mistake to forget an `await` there.

This would 100% break Marketplace searches, but I'm still not sure why you would be seeing your Craigslist searches affected. Regardless, you could try pulling latest and seeing if maybe it helps.

**Comment by stephanlensky** [comment] 2024-02-23 04:00
re: the original issue in this thread (future exceptions):

After I recently started getting some very similar errors, I found that they are likely caused by a bug in pyppeteer. Since pyppeteer is now unmaintained, I decided to switch this project over to [playwright](https://playwright.dev/), so we should no longer see any errors like this.

Closing this issue for now.

**Closed by stephanlensky** 2024-02-23 04:00 UTC

**Comment by KenwoodFox** [comment] 2024-02-23 18:31
Thanks so much, hope to see things working solidly now!
